controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

    
app_afficher_donnees:
    path: '/afficher-donnees'
    controller: App\Controller\MonController::afficherDonnees




